- name: Ensure installation directory
  file:
    path: "{{ repo_dir }}"
    state: directory

- name: Fetch operator-sdk
  ansible.builtin.uri:
    url: https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_sdk_version }}/operator-sdk_linux_amd64
    dest: "{{ repo_dir }}/operator-sdk"
    mode: "755"
    status_code:
      - 200
      - 304

- name: Check if OLM is installed
  ansible.builtin.command:
    "{{ repo_dir }}/operator-sdk olm status"
  register: olm_status
  failed_when: olm_status.rc not in [0, 1]

- name: Install OLM with SDK
  ansible.builtin.command:
    "{{ repo_dir }}/operator-sdk olm install --version {{ olm_version }}"
  when: olm_status.rc != 0

- name: Ensure privileged SCC for OLM
  ansible.builtin.command:
    oc adm policy add-scc-to-user privileged system:serviceaccount:olm:default
