---
- name: Install DNSMasq
  become: true
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: Change DNSMasq configuration
  become: true
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^#server=/3.168.192.in-addr.arpa/10.1.2.3"
      line: "server={{ cloudprovider_dns | default(public_dns) | random }}"
    - regexp: '^# server=10.1.2.3@eth1'
      line: "server={{ public_dns | random}}"
    - regexp: "^interface=lo"
      line: "#interface=lo"
    - regexp: "^#address=\/double-click.net\/127.0.0.1"
      line: "address=/{{ fqdn }}/127.0.0.1"
  notify: Restart DNSMasq service

- name: Add dnsmasq rule for NetworkManager
  become: true
  ansible.builtin.copy:
    content: |
      [main]
      dns=dnsmasq
    dest: /etc/NetworkManager/conf.d/00-microshift-use-dnsmasq.conf
  notify: Reload NetworkManager

- name: Change resolv.conf
  become: true
  ansible.builtin.copy:
    content: |
      # NOTE: The nameserver ip addresses are set in /etc/dnsmasq.conf
      nameserver 127.0.0.1
    dest: /etc/resolv.conf

- name: Flush handlers
  meta: flush_handlers
